Return-Path: <linux-afs-bounces+lists+linux-afs=lfdr.de@lists.infradead.org>
X-Original-To: lists+linux-afs@lfdr.de
Delivered-To: lists+linux-afs@lfdr.de
Received: from bombadil.infradead.org (bombadil.infradead.org [IPv6:2607:7c80:54:e::133])
	by mail.lfdr.de (Postfix) with ESMTPS id DC06B2DEED
	for <lists+linux-afs@lfdr.de>; Wed, 29 May 2019 15:52:28 +0200 (CEST)
DKIM-Signature: v=1; a=rsa-sha256; q=dns/txt; c=relaxed/relaxed;
	d=lists.infradead.org; s=bombadil.20170209; h=Sender:
	Content-Transfer-Encoding:Content-Type:Cc:List-Subscribe:List-Help:List-Post:
	List-Archive:List-Unsubscribe:List-Id:MIME-Version:References:In-Reply-To:
	Subject:To:From:Message-ID:Date:Reply-To:Content-ID:Content-Description:
	Resent-Date:Resent-From:Resent-Sender:Resent-To:Resent-Cc:Resent-Message-ID:
	List-Owner; bh=nS9shsCJ7gu4xPJnK+1h5MCFfC8NKAAoFzv5F7y22NM=; b=DadK+/Gwv00I0N
	vo4B4fooBOSvpg7QtKNqoKzyxKUDwmlZrkwIUSETA06sinB5FL9Hcw9AwFLskMEFUEuhcLjeXhVlv
	r1g2sd3Ul7PmuY9J17YL9EjXwDPbSD6M+vpMJwcBMmz4gyJPgG+IOzVo5562AKf+f32mKeN4m+zUZ
	G0CoC3sBHMlzooh/usvx+GsJVHN/ee4Edjc3g+NjUey32Ri9XAXm04zKUseeVz74f48YF85OTz1e0
	OOo0b4ZztfBNtnFWoZl9LPerMBFY5WnGSHzPe+DZ2Hq0EeU7btuzuHCIGMtPQYdXpwmFa3cOxC1bm
	n8rfg6X2wwpc4N8108HQ==;
Received: from localhost ([127.0.0.1] helo=bombadil.infradead.org)
	by bombadil.infradead.org with esmtp (Exim 4.90_1 #2 (Red Hat Linux))
	id 1hVz09-0006EH-MU; Wed, 29 May 2019 13:52:21 +0000
Received: from mx2.suse.de ([195.135.220.15] helo=mx1.suse.de)
 by bombadil.infradead.org with esmtps (Exim 4.90_1 #2 (Red Hat Linux))
 id 1hVvUP-0006TX-JH
 for linux-afs@lists.infradead.org; Wed, 29 May 2019 10:07:23 +0000
X-Virus-Scanned: by amavisd-new at test-mx.suse.de
Received: from relay2.suse.de (unknown [195.135.220.254])
 by mx1.suse.de (Postfix) with ESMTP id E36FFAEFF;
 Wed, 29 May 2019 10:07:15 +0000 (UTC)
Date: Wed, 29 May 2019 12:07:13 +0200
Message-ID: <s5hsgsxtvzi.wl-tiwai@suse.de>
From: Takashi Iwai <tiwai@suse.de>
To: "Takashi Sakamoto" <o-takashi@sakamocchi.jp>
Subject: Re: [PATCH 4/5] ALSA: fireface: Use ULL suffixes for 64-bit constants
In-Reply-To: <20190529095730.GA7089@workstation>
References: <20190528142424.19626-1-geert@linux-m68k.org>
 <20190528142424.19626-5-geert@linux-m68k.org>
 <20190529095730.GA7089@workstation>
User-Agent: Wanderlust/2.15.9 (Almost Unreal) SEMI/1.14.6 (Maruoka)
 FLIM/1.14.9 (=?UTF-8?B?R29qxY0=?=) APEL/10.8 Emacs/25.3
 (x86_64-suse-linux-gnu) MULE/6.0 (HANACHIRUSATO)
MIME-Version: 1.0 (generated by SEMI 1.14.6 - "Maruoka")
X-CRM114-Version: 20100106-BlameMichelson ( TRE 0.8.0 (BSD) ) MR-646709E3 
X-CRM114-CacheID: sfid-20190529_030721_778632_C51B891F 
X-CRM114-Status: GOOD (  12.48  )
X-Spam-Score: -2.3 (--)
X-Spam-Report: SpamAssassin version 3.4.2 on bombadil.infradead.org summary:
 Content analysis details:   (-2.3 points)
 pts rule name              description
 ---- ---------------------- --------------------------------------------------
 -2.3 RCVD_IN_DNSWL_MED      RBL: Sender listed at https://www.dnswl.org/,
 medium trust [195.135.220.15 listed in list.dnswl.org]
 0.0 SPF_HELO_NONE          SPF: HELO does not publish an SPF Record
 -0.0 SPF_PASS               SPF: sender matches SPF record
X-Mailman-Approved-At: Wed, 29 May 2019 06:52:19 -0700
X-BeenThere: linux-afs@lists.infradead.org
X-Mailman-Version: 2.1.21
Precedence: list
List-Id: "Linux AFS client discussion list." <linux-afs.lists.infradead.org>
List-Unsubscribe: <http://lists.infradead.org/mailman/options/linux-afs>,
 <mailto:linux-afs-request@lists.infradead.org?subject=unsubscribe>
List-Archive: <http://lists.infradead.org/pipermail/linux-afs/>
List-Post: <mailto:linux-afs@lists.infradead.org>
List-Help: <mailto:linux-afs-request@lists.infradead.org?subject=help>
List-Subscribe: <http://lists.infradead.org/mailman/listinfo/linux-afs>,
 <mailto:linux-afs-request@lists.infradead.org?subject=subscribe>
Cc: linux-block@vger.kernel.org, alsa-devel@alsa-project.org,
 Arnd Bergmann <arnd@arndb.de>, linux-kernel@vger.kernel.org,
 "Mohit P . Tahiliani" <tahiliani@nitk.edu.in>,
 Clemens Ladisch <clemens@ladisch.de>, Jamal Hadi Salim <jhs@mojatatu.com>,
 linux-afs@lists.infradead.org, David Howells <dhowells@redhat.com>,
 Jiri Pirko <jiri@mellanox.com>, netdev@vger.kernel.org,
 Geert Uytterhoeven <geert@linux-m68k.org>,
 Eran Ben Elisha <eranbe@mellanox.com>, Joe Perches <joe@perches.com>,
 Cong Wang <xiyou.wangcong@gmail.com>, Matias Bjorling <mb@lightnvm.io>,
 Jaroslav Kysela <perex@perex.cz>, "David S . Miller" <davem@davemloft.net>,
 Dan Carpenter <dan.carpenter@oracle.com>,
 Igor Konopko <igor.j.konopko@intel.com>
Content-Type: text/plain; charset="utf-8"
Content-Transfer-Encoding: base64
Sender: "linux-afs" <linux-afs-bounces@lists.infradead.org>
Errors-To: linux-afs-bounces+lists+linux-afs=lfdr.de@lists.infradead.org

T24gV2VkLCAyOSBNYXkgMjAxOSAxMTo1NzozMSArMDIwMCwKVGFrYXNoaSBTYWthbW90byB3cm90
ZToKPiAKPiBIaSwKPiAKPiBPbiBUdWUsIE1heSAyOCwgMjAxOSBhdCAwNDoyNDoyM1BNICswMjAw
LCBHZWVydCBVeXR0ZXJob2V2ZW4gd3JvdGU6Cj4gPiBXaXRoIGdjYyA0LjE6Cj4gPiAKPiA+ICAg
ICBzb3VuZC9maXJld2lyZS9maXJlZmFjZS9mZi1wcm90b2NvbC1sYXR0ZXIuYzogSW4gZnVuY3Rp
b24g4oCYbGF0dGVyX3N3aXRjaF9mZXRjaGluZ19tb2Rl4oCZOgo+ID4gICAgIHNvdW5kL2ZpcmV3
aXJlL2ZpcmVmYWNlL2ZmLXByb3RvY29sLWxhdHRlci5jOjk3OiB3YXJuaW5nOiBpbnRlZ2VyIGNv
bnN0YW50IGlzIHRvbyBsYXJnZSBmb3Ig4oCYbG9uZ+KAmSB0eXBlCj4gPiAgICAgc291bmQvZmly
ZXdpcmUvZmlyZWZhY2UvZmYtcHJvdG9jb2wtbGF0dGVyLmM6IEluIGZ1bmN0aW9uIOKAmGxhdHRl
cl9iZWdpbl9zZXNzaW9u4oCZOgo+ID4gICAgIHNvdW5kL2ZpcmV3aXJlL2ZpcmVmYWNlL2ZmLXBy
b3RvY29sLWxhdHRlci5jOjE3MDogd2FybmluZzogaW50ZWdlciBjb25zdGFudCBpcyB0b28gbGFy
Z2UgZm9yIOKAmGxvbmfigJkgdHlwZQo+ID4gICAgIHNvdW5kL2ZpcmV3aXJlL2ZpcmVmYWNlL2Zm
LXByb3RvY29sLWxhdHRlci5jOjE5Nzogd2FybmluZzogaW50ZWdlciBjb25zdGFudCBpcyB0b28g
bGFyZ2UgZm9yIOKAmGxvbmfigJkgdHlwZQo+ID4gICAgIHNvdW5kL2ZpcmV3aXJlL2ZpcmVmYWNl
L2ZmLXByb3RvY29sLWxhdHRlci5jOjIwNTogd2FybmluZzogaW50ZWdlciBjb25zdGFudCBpcyB0
b28gbGFyZ2UgZm9yIOKAmGxvbmfigJkgdHlwZQo+ID4gICAgIHNvdW5kL2ZpcmV3aXJlL2ZpcmVm
YWNlL2ZmLXByb3RvY29sLWxhdHRlci5jOiBJbiBmdW5jdGlvbiDigJhsYXR0ZXJfZmluaXNoX3Nl
c3Npb27igJk6Cj4gPiAgICAgc291bmQvZmlyZXdpcmUvZmlyZWZhY2UvZmYtcHJvdG9jb2wtbGF0
dGVyLmM6MjE0OiB3YXJuaW5nOiBpbnRlZ2VyIGNvbnN0YW50IGlzIHRvbyBsYXJnZSBmb3Ig4oCY
bG9uZ+KAmSB0eXBlCj4gPiAKPiA+IEZpeCB0aGlzIGJ5IGFkZGluZyB0aGUgbWlzc2luZyAiVUxM
IiBzdWZmaXhlcy4KPiA+IEFkZCB0aGUgc2FtZSBzdWZmaXggdG8gdGhlIGxhc3QgY29uc3RhbnQs
IHRvIG1haW50YWluIGNvbnNpc3RlbmN5Lgo+ID4gCj4gPiBGaXhlczogZmQxY2M5ZGU2NGMyY2E2
YyAoIkFMU0E6IGZpcmVmYWNlOiBhZGQgc3VwcG9ydCBmb3IgRmlyZWZhY2UgVUNYIikKPiA+IFNp
Z25lZC1vZmYtYnk6IEdlZXJ0IFV5dHRlcmhvZXZlbiA8Z2VlcnRAbGludXgtbTY4ay5vcmc+Cj4g
PiAtLS0KPiA+ICBzb3VuZC9maXJld2lyZS9maXJlZmFjZS9mZi1wcm90b2NvbC1sYXR0ZXIuYyB8
IDEwICsrKysrLS0tLS0KPiA+ICAxIGZpbGUgY2hhbmdlZCwgNSBpbnNlcnRpb25zKCspLCA1IGRl
bGV0aW9ucygtKQo+IAo+IFRoYW5rcyBmb3IgeW91ciBjYXJlLgo+IAo+IFJldmlld2VkLWJ5OiBU
YWthc2hpIFNha2Ftb3RvIDxvLXRha2FzaGlAc2FrYW1vY2NoaS5qcD4KCkFwcGxpZWQgdG8gc291
bmQgZ2l0IHRyZWUgbm93LiAgVGhhbmtzLgoKClRha2FzaGkKCl9fX19fX19fX19fX19fX19fX19f
X19fX19fX19fX19fX19fX19fX19fX19fX19fCmxpbnV4LWFmcyBtYWlsaW5nIGxpc3QKaHR0cDov
L2xpc3RzLmluZnJhZGVhZC5vcmcvbWFpbG1hbi9saXN0aW5mby9saW51eC1hZnMK
